export enum actionType {
    UPDATE_PLAYLIST = 'UPDATE_PLAYLIST',
    UPDATE_QUEUE = 'UPDATE_QUEUE',
    UPDATE_CURRENT_SONG = 'UPDATE_CURRENT_SONG',
    SHUFFLE = 'SHUFFLE',
    UPDATE_ISPLAYING = 'UPDATE_ISPLAYING',
}